import { FC } from 'react';
import Link from 'next/link';

interface ErrorDisplayProps {
  missingParams: string[];
}

export const ErrorDisplay: FC<ErrorDisplayProps> = ({ missingParams }) => {
  return (
    <div className="w-full max-w-2xl">
      <div className="text-center mb-8">
        <h1 className="text-2xl font-bold mt-16">Invalid Tip Request</h1>
      </div>

      <div className="bg-destructive/10 border-l-4 border-destructive text-destructive p-4 mb-6 rounded">
        <h2 className="font-bold text-lg mb-2">Missing Required Parameters</h2>
        <p className="mb-4">
          This tip link is incomplete or invalid. The following required parameters are missing:
        </p>
        <ul className="list-disc pl-5 mb-4">
          {missingParams.map((param) => (
            <li key={param} className="mb-1">
              <code className="bg-muted px-1 py-0.5 rounded">{param}</code>
              {param === 'receiver_user_id' && ' - Discord ID of the tip recipient'}
              {param === 'receiver_username' && ' - Username of the tip recipient'}
              {param === 'amount' && ' - Valid USDC amount to tip'}
            </li>
          ))}
        </ul>
        <p className="text-sm">
          Tip links should be generated by the Discord bot and include all necessary information.
        </p>
      </div>

      <div className="bg-muted p-6 rounded-lg shadow">
        <h3 className="font-semibold text-lg mb-3">What can I do?</h3>
        <ul className="space-y-2">
          <li>• Return to Discord and use the correct tip command</li>
          <li>• Contact the person who sent you this link</li>
          <li>
            • <Link href="/docs" className="text-primary underline">
                View documentation
              </Link> for proper usage
          </li>
        </ul>
      </div>

      <div className="mt-6 text-center">
        <p className="text-sm text-muted-foreground">
          A properly formatted tip URL should look like:
          <code className="text-xs bg-muted p-1 rounded block mt-2 overflow-x-auto whitespace-nowrap py-2 px-3">
            https://verify-bot.gib.work/tip?receiver_user_id=123456789&receiver_username=username&amount=5
          </code>
        </p>
      </div>
    </div>
  );
};

